# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: platform
  description: Turn data into revenue
  homepage: https://mytiki.com/
  topics: mytiki, platform
  private: false
  has_projects: true
  has_discussions: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
